version: '3'
services:


  # db is is db folder
  db:
    build: src/db/.
    command: ['--default-authentication-plugin=mysql_native_password','--character-set-server=latin1','--collation-server=latin1_swedish_ci']
    restart: always

  # Application Dockerfile is in same folder which is .
  app:
    build: .
    stdin_open: true
    tty: true

